from pathlib import Path
import json
import unittest


ROOT = Path(__file__).resolve().parents[1]


def read_frontend_sources(*suffixes):
    parts = []
    for path in sorted((ROOT / "src" / "frontend").rglob("*")):
        if path.is_file() and path.suffix in suffixes:
            parts.append(path.read_text(encoding="utf-8"))
    return "\n".join(parts)


class FrontendStaticTests(unittest.TestCase):
    def test_vue_app_project_files_exist(self):
        package_json = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
        self.assertEqual(package_json["scripts"]["dev"], "vite --host 127.0.0.1")
        self.assertEqual(package_json["scripts"]["build"], "vite build")
        self.assertIn("vue", package_json["dependencies"])
        self.assertIn("vite", package_json["devDependencies"])
        self.assertIn("@vitejs/plugin-vue", package_json["devDependencies"])
        self.assertTrue((ROOT / "index.html").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "main.js").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "App.vue").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "api.js").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "graph.js").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "components" / "NodeShelf.vue").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "components" / "GraphCanvas.vue").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "components" / "ResultRail.vue").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "views" / "ProvidersView.vue").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "views" / "PersonasView.vue").exists())
        self.assertTrue((ROOT / "src" / "frontend" / "views" / "ChatView.vue").exists())
        vite_config = (ROOT / "vite.config.js").read_text(encoding="utf-8")
        self.assertIn("@vitejs/plugin-vue", vite_config)
        self.assertIn("vue/dist/vue.esm-bundler.js", vite_config)
        self.assertIn("outDir: \"frontend/dist\"", vite_config)

    def test_planner_page_references_assets_and_nodes(self):
        html = (ROOT / "src" / "frontend" / "App.vue").read_text(encoding="utf-8")
        js = (
            read_frontend_sources(".vue", ".js")
            + (ROOT / "src" / "frontend" / "graph.js").read_text(encoding="utf-8")
            + (ROOT / "src" / "frontend" / "api.js").read_text(encoding="utf-8")
        )
        app_source = (ROOT / "src" / "frontend" / "App.vue").read_text(encoding="utf-8")
        component_html = read_frontend_sources(".vue")
        html = component_html

        self.assertIn("FlainBot Node Planner", html)
        self.assertIn("class=\"app-shell\"", html)
        self.assertIn("class=\"workbench-topbar\"", html)
        topbar_html = html.split("<header class=\"workbench-topbar\">", 1)[1].split("</header>", 1)[0]
        toolbar_html = html.split("<div class=\"canvas-toolbar\">", 1)[1].split("</div>", 1)[0]
        self.assertIn("<h1 class=\"workbench-title\">FlainBot</h1>", topbar_html)
        self.assertNotIn("class=\"topbar-actions\"", topbar_html)
        self.assertNotIn("id=\"save-graph\"", topbar_html)
        self.assertNotIn("id=\"reset-graph\"", topbar_html)
        self.assertIn("id=\"save-graph\"", toolbar_html)
        self.assertIn("id=\"reset-graph\"", toolbar_html)
        self.assertIn("id=\"status-message\"", toolbar_html)
        self.assertIn("class=\"planner-workbench result-collapsed view\"", html)
        self.assertIn(":data-route=\"view.id\"", html)
        self.assertIn("{id: \"planner\", label: \"Planner\"}", js)
        self.assertIn("{id: \"providers\", label: \"Providers\"}", js)
        self.assertIn("{id: \"personas\", label: \"Personas\"}", js)
        self.assertIn("{id: \"chat\", label: \"Chat\"}", js)
        self.assertIn("data-view=\"providers\"", html)
        self.assertIn("data-view=\"personas\"", html)
        self.assertIn("id=\"provider-form\"", html)
        self.assertIn("id=\"provider-list\"", html)
        self.assertIn("data-edit-provider", html)
        self.assertIn("id=\"persona-form\"", html)
        self.assertIn("id=\"persona-list\"", html)
        self.assertIn("data-edit-persona", html)
        self.assertIn("name=\"persona_id\"", html)
        self.assertIn("name=\"system_prompt\"", html)
        self.assertIn("name=\"begin_dialogs\"", html)
        self.assertIn("name=\"tools_json\"", html)
        self.assertIn("name=\"skills_json\"", html)
        self.assertIn("name=\"custom_error_message\"", html)
        self.assertIn("name=\"format\"", html)
        self.assertIn("openai_chat", html)
        self.assertIn("anthropic_messages", html)
        self.assertIn("placeholder=\"provider-id\"", html)
        self.assertIn("placeholder=\"provider-base-url\"", html)
        self.assertIn("placeholder=\"your-model-name\"", html)
        self.assertNotIn("placeholder=\"openai_main\"", html)
        self.assertNotIn("placeholder=\"https://api.openai.com/v1\"", html)
        self.assertNotIn("placeholder=\"gpt-4.1-mini\"", html)
        self.assertIn("id=\"node-search\"", html)
        self.assertIn("id=\"package-filter-options\"", html)
        self.assertIn("id=\"input-type-filter-options\"", html)
        self.assertIn("id=\"output-type-filter-options\"", html)
        self.assertIn("id=\"node-filter-dropdown\"", html)
        self.assertIn("id=\"node-filter-summary\"", html)
        self.assertIn("id=\"node-preview-popover\"", html)
        self.assertIn("data-filter-label=\"Package\"", html)
        self.assertIn("data-filter-label=\"Input type\"", html)
        self.assertIn("data-filter-label=\"Output type\"", html)
        self.assertEqual(html.count("class=\"filter-dropdown\""), 1)
        self.assertNotIn("details id=\"node-filter-dropdown\" class=\"filter-dropdown\" open", html)
        self.assertNotIn("<select id=\"package-filter\"", html)
        self.assertNotIn("<select id=\"input-type-filter\"", html)
        self.assertNotIn("<select id=\"output-type-filter\"", html)
        self.assertNotIn("type=\"password\"", html)
        self.assertIn("id=\"result-panel\"", html)
        self.assertIn("id=\"toggle-result-panel\"", html)
        self.assertIn("<div id=\"python-panel\" class=\"result-section\">", html)
        result_panel_html = html.split("<aside id=\"result-panel\"", 1)[1].split("</aside>", 1)[0]
        self.assertNotIn("<details", result_panel_html)
        self.assertNotIn("<summary>Generated Python</summary>", html)
        self.assertIn("Generated Python", html)
        self.assertIn("save-graph", html)
        self.assertIn("graph-canvas", html)
        self.assertIn("data-canvas-space", html)
        self.assertIn("edge-layer", html)
        self.assertNotIn("<marker", html)
        self.assertNotIn("property-editor", html)
        graph_canvas_html = (ROOT / "src" / "frontend" / "components" / "GraphCanvas.vue").read_text(encoding="utf-8")
        node_layer_html = graph_canvas_html.split("<div id=\"node-layer\"", 1)[1].split("</div>\n      </div>", 1)[0]
        self.assertIn("node-remove-dot", node_layer_html)
        self.assertNotIn("node-remove-triangle", node_layer_html)
        self.assertIn("title=\"Remove node\"", node_layer_html)
        self.assertNotIn("data-action=\"remove\"", node_layer_html)
        self.assertNotIn(">Remove</button>", node_layer_html)
        self.assertIn("build_graph_from_config", js)
        self.assertNotIn("ChatInputNode(", js)
        self.assertNotIn("ChatOutputNode(", js)
        self.assertNotIn("PromptBuilderNode(", js)
        self.assertNotIn("PersonaNode(", js)
        self.assertIn("persona", js)
        self.assertIn("persona_id", js)
        self.assertIn("personas", js)
        self.assertIn("\"/api/personas\"", js)
        self.assertIn("loadPersonas", js)
        self.assertIn("savePersonas", js)
        self.assertIn("personas.value", js)
        self.assertIn("editPersona", js)
        self.assertIn("personaEditingId", js)
        self.assertIn("personas.value.filter((item) => item.persona_id !== (personaEditingId.value || persona.persona_id))", js)
        self.assertIn("JSON.stringify(persona.tools || [], null, 2)", js)
        self.assertIn("node.type === 'persona'", js)
        self.assertIn("loadNodeCatalog", js)
        self.assertIn("nodeCatalog.value = await loadNodeCatalog()", js)
        self.assertIn("generatePython", js)
        self.assertIn("edges", js)
        self.assertIn("GraphExecutor", js)
        self.assertIn("nodes: graph.nodes.map", js)
        self.assertIn("pointerdown", js)
        self.assertIn("connectionDrag", js)
        self.assertIn("startConnectionDrag", js)
        self.assertIn("edgeToReplaceForPort", js)
        self.assertIn("removeEdgeAt", js)
        self.assertNotIn("startEdgeEndpointDrag", js)
        self.assertIn("moveConnectionDrag", js)
        self.assertIn("finishConnectionDrag", js)
        self.assertIn("preview-connection", js)
        self.assertNotIn("edge-handle", html)
        self.assertIn("edge-arrow", html)
        self.assertIn("data-compatible", js)
        self.assertNotIn("handlePortClick", js)
        self.assertIn("viewportState", js)
        self.assertIn("canvasSpaceStyle", js)
        self.assertIn("wheel", js)
        self.assertIn("startCanvasPan", js)
        self.assertIn("data-port", js)
        self.assertIn("connectionArrow", js)
        self.assertIn("\"/api/graph\"", js)
        self.assertIn("\"/api/nodes\"", js)
        self.assertIn("loadNodeCatalog", js)
        self.assertIn("nodeSearch", js)
        self.assertIn("selectedPackage", js)
        self.assertIn("selectedInputType", js)
        self.assertIn("selectedOutputType", js)
        self.assertIn("filterNodeCatalog", js)
        self.assertIn("filterOptionValues", js)
        self.assertIn("nodeFilterSummary", js)
        self.assertIn("filterOptions", js)
        self.assertIn("nodeMatchesFilters", js)
        self.assertIn("selectedPackage", js)
        self.assertIn("selectedInputType", js)
        self.assertIn("selectedOutputType", js)
        self.assertIn("flattenNodeCatalog", js)
        self.assertIn("collectCatalogNodes", js)
        self.assertIn("portName", js)
        self.assertIn("portType", js)
        self.assertIn("portsText", js)
        self.assertIn("nodePreview", js)
        self.assertIn("node-preview", js)
        self.assertIn("nodePreview", js)
        self.assertIn("showNodePreview", js)
        self.assertIn("moveNodePreview", js)
        self.assertIn("hideNodePreview", js)
        self.assertIn("graph-node preview-node", js)
        self.assertIn("node-header", js)
        self.assertIn("node-body", js)
        self.assertIn("PortList", js)
        self.assertIn("draggable=\"true\"", js)
        self.assertIn("dragstart", js)
        self.assertIn("handleNodeCardDragStart", js)
        self.assertIn("handleCanvasDrop", js)
        self.assertIn("dataTransfer.setData", js)
        self.assertIn("dataTransfer.getData", js)
        self.assertIn("@dragover.prevent", html)
        self.assertIn("@drop.prevent=\"$emit('canvas-drop', $event)\"", html)
        self.assertIn("@canvas-drop=\"handleCanvasDrop\"", app_source)
        self.assertIn("mousemove", js)
        self.assertIn("mouseleave", js)
        self.assertNotIn("add-node-button", js)
        self.assertNotIn("Add node", html)
        self.assertIn("packageId", js)
        self.assertIn("packageTitle", js)
        self.assertIn("data-port-type", js)
        self.assertIn("CatalogGroup", js)
        self.assertIn("node-package", js)
        self.assertIn("node-group", js)
        self.assertIn("import NodeShelf from \"./components/NodeShelf.vue\"", app_source)
        self.assertIn("import GraphCanvas from \"./components/GraphCanvas.vue\"", app_source)
        self.assertIn("import ResultRail from \"./components/ResultRail.vue\"", app_source)
        self.assertIn("import ProvidersView from \"./views/ProvidersView.vue\"", app_source)
        self.assertIn("import PersonasView from \"./views/PersonasView.vue\"", app_source)
        self.assertIn("import ChatView from \"./views/ChatView.vue\"", app_source)
        self.assertNotIn("const PortList = defineComponent", app_source)
        self.assertNotIn("const NodeCard = defineComponent", app_source)
        self.assertNotIn("const CatalogGroup = defineComponent", app_source)
        self.assertNotIn("categoryForNode", js)
        self.assertIn("node-search", js)
        self.assertIn("generatedPython", js)
        self.assertIn("updateProperty", js)
        self.assertIn("resultRailCollapsed", js)
        self.assertIn("toggleResultPanel", js)
        self.assertIn("resultRailCollapsed", js)
        self.assertIn("result-collapsed", js)
        self.assertIn("result-rail collapsed", js)
        self.assertIn("Could not load node catalog", js)
        self.assertIn("const nodeCatalog = ref([])", js)
        self.assertIn("nodeCatalog.value = await loadNodeCatalog()", js)
        self.assertIn("loadGraph", js)
        self.assertIn("\"/api/graph\"", js)
        self.assertIn("restoreGraph(savedGraph)", js)
        self.assertIn("function restoreGraph(config)", js)
        self.assertIn("const spec = flatNodeCatalog.value.find((node) => node.type === nodeConfig.type)", js)
        self.assertIn("graph.nodes = (config.nodes || []).flatMap", js)
        self.assertIn("graph.edges = config.edges || []", js)
        self.assertIn("filterNodeCatalog(nodeCatalog.value", js)
        self.assertNotIn("const nodeCatalog = [", js)
        self.assertIn("setStatus(", js)
        self.assertIn("Could not reach FlainBot server", js)
        self.assertIn("127.0.0.1:8765", js)
        self.assertIn("provider_call", js)
        self.assertIn("provider_id", js)
        self.assertIn("providers", js)
        self.assertIn("\"/api/providers\"", js)
        self.assertIn("loadProviders", js)
        self.assertIn("saveProviders", js)
        self.assertIn("providers.value", js)
        self.assertIn("editProvider", js)
        self.assertIn("providerEditingId", js)
        self.assertIn("providers.value.filter((item) => item.id !== (providerEditingId.value || provider.id))", js)
        self.assertIn("node.type === 'provider_call'", js)
        self.assertIn("latestNodeOutputs", js)
        self.assertIn("nodeDisplayText(node)", js)
        self.assertIn("class=\"display-node-result\"", html)
        self.assertIn("node.type === 'display_data'", html)
        self.assertIn("const form = event.currentTarget", js)
        self.assertIn("form.reset()", js)
        self.assertNotIn("event.currentTarget.reset()", js)
        self.assertNotIn("type=\"password\"", js)
        self.assertNotIn("type=\\\"password\\\"", js)
        self.assertNotIn("node.type === \"openai\" || node.type === \"anthropic\"", js)
        self.assertIn("class=\"node-properties\"", js)
        self.assertIn("node-properties", js)
        self.assertIn("autocomplete=\"off\"", js)
        self.assertIn("event.preventDefault()", js)
        css = (ROOT / "src" / "frontend" / "styles.css").read_text(encoding="utf-8")
        self.assertIn(".node-filters", css)
        self.assertIn(".node-preview", css)
        self.assertIn(".personas-shell", css)
        self.assertIn("position: fixed", css)
        self.assertIn("max-width: calc(100vw - 24px)", css)
        self.assertIn("max-height: calc(100vh - 24px)", css)
        self.assertIn(".node-preview .preview-node", css)
        self.assertIn(".card-actions", css)
        self.assertIn(".node-remove-dot", css)
        self.assertIn("border-radius: 50%", css)
        self.assertIn("min-height: 12px", css)
        self.assertNotIn("node-remove-triangle", css)
        self.assertNotIn("clip-path: polygon(50% 0, 0 100%, 100% 100%)", css)
        self.assertIn("top: 9px", css)
        self.assertIn("right: 9px", css)
        self.assertNotIn("border-top: 18px solid var(--danger)", css)
        self.assertIn("width: 100%", css)
        self.assertNotIn(".node-card:hover .node-preview", css)
        self.assertNotIn(".node-preview-card", css)
        self.assertNotIn(".add-node-button", css)

    def test_chat_view_is_in_single_index_shell(self):
        html = read_frontend_sources(".vue")
        js = (
            read_frontend_sources(".vue", ".js")
            + (ROOT / "src" / "frontend" / "api.js").read_text(encoding="utf-8")
        )
        css = (ROOT / "src" / "frontend" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("FlainBot Chat", html)
        self.assertIn("data-view=\"chat\"", html)
        self.assertIn("id=\"session-select\"", html)
        self.assertIn("id=\"new-session\"", html)
        self.assertIn("id=\"delete-session\"", html)
        self.assertIn("session.id", html)
        self.assertIn("id=\"chat-form\"", html)
        self.assertIn("id=\"messages\"", html)
        self.assertIn("<details class=\"trace-panel\">", html)
        self.assertNotIn("class=\"trace-size-control\"", html)
        self.assertNotIn("traceSizeOptions", js)
        self.assertNotIn("chat.css", html)
        self.assertNotIn("chat.js", html)
        self.assertIn("setActiveView", js)
        self.assertIn("hashchange", js)
        self.assertIn("\"/api/chat\"", js)
        self.assertIn("\"/api/sessions\"", js)
        self.assertIn("loadSessions", js)
        self.assertIn("saveSessions", js)
        self.assertIn("deleteSession", js)
        self.assertIn("activeSessionId", js)
        self.assertIn("sessions", js)
        self.assertIn("sendChatMessage(message, activeSessionId.value)", js)
        self.assertIn("session_id", js)
        self.assertIn("renderTrace", js)
        self.assertIn("payload.replies || [payload.reply]", js)
        self.assertIn("payload.trace", js)
        self.assertIn("trace-panel", js)
        self.assertIn("127.0.0.1:8765", js)
        self.assertIn(".chat-shell", css)
        self.assertIn(".trace-panel", css)
        self.assertIn(".trace-panel[open]", css)
        self.assertIn(".trace-panel:not([open])", css)
        trace_closed_css = css.split(".trace-panel:not([open])", 1)[1].split("}", 1)[0]
        trace_open_css = css.split(".trace-panel[open]", 1)[1].split("}", 1)[0]
        trace_pre_css = css.split(".trace-panel pre", 1)[1].split("}", 1)[0]
        self.assertIn("overflow-wrap: anywhere", css)
        self.assertIn("white-space: pre-wrap", css)
        self.assertIn("height: auto", trace_closed_css)
        self.assertIn("resize: none", trace_closed_css)
        self.assertIn("resize: both", trace_open_css)
        self.assertIn("min-width: 180px", trace_open_css)
        self.assertIn("\n  height: 220px;\n", trace_open_css)
        self.assertIn("min-height: 120px", trace_pre_css)
        self.assertIn("grid-template-rows: auto minmax(0, 1fr)", trace_open_css)
        self.assertIn("height: calc(100% - 24px)", trace_pre_css)
        self.assertNotIn("max-height: 220px", trace_pre_css)
        self.assertNotIn(".trace-panel pre {\n  width: 100%;", css)
        self.assertNotIn(".trace-panel.trace-size-small pre", css)
        self.assertNotIn(".trace-panel.trace-size-medium pre", css)
        self.assertNotIn(".trace-panel.trace-size-large pre", css)
        self.assertIn(".workbench-title", css)
        self.assertIn("justify-content: center", css)
        self.assertIn(".canvas-actions", css)
        self.assertIn("html,\nbody", css)
        self.assertIn("overflow: hidden", css)
        self.assertIn("height: 100vh", css)
        self.assertIn("main {\n  min-height: 0;\n  overflow: hidden;", css)
        self.assertIn("grid-template-rows: auto minmax(0, 1fr)", css)
        self.assertIn("overflow-y: auto", css)
        self.assertIn(".planner-workbench.result-collapsed", css)
        self.assertIn(".result-rail.collapsed .result-toggle", css)
        self.assertIn("height: 100%", css)
        self.assertIn("writing-mode: vertical-rl", css)
        self.assertNotIn(".result-toggle-hint", css)
        self.assertNotIn(".result-section > summary", css)
        self.assertIn("height: 100%", css)

    def test_standalone_chat_assets_were_removed(self):
        self.assertFalse((ROOT / "frontend" / "chat.html").exists())
        self.assertFalse((ROOT / "frontend" / "chat.js").exists())
        self.assertFalse((ROOT / "frontend" / "chat.css").exists())
        self.assertFalse((ROOT / "frontend" / "app.js").exists())
        self.assertFalse((ROOT / "frontend" / "index.html").exists())
        self.assertFalse((ROOT / "frontend" / "styles.css").exists())


if __name__ == "__main__":
    unittest.main()
