from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class FrontendStaticTests(unittest.TestCase):
    def test_planner_page_references_assets_and_nodes(self):
        html = (ROOT / "frontend" / "index.html").read_text(encoding="utf-8")
        js = (ROOT / "frontend" / "app.js").read_text(encoding="utf-8")

        self.assertIn("FlainBot Node Planner", html)
        self.assertIn("styles.css", html)
        self.assertIn("app.js", html)
        self.assertIn("class=\"app-shell\"", html)
        self.assertIn("class=\"workbench-topbar\"", html)
        self.assertIn("class=\"planner-workbench result-collapsed view\"", html)
        self.assertIn("data-route=\"planner\"", html)
        self.assertIn("data-route=\"providers\"", html)
        self.assertIn("data-route=\"chat\"", html)
        self.assertIn("data-view=\"providers\"", html)
        self.assertIn("id=\"provider-form\"", html)
        self.assertIn("id=\"provider-list\"", html)
        self.assertIn("name=\"format\"", html)
        self.assertIn("openai_chat", html)
        self.assertIn("anthropic_messages", html)
        self.assertIn("id=\"node-search\"", html)
        self.assertIn("id=\"result-panel\"", html)
        self.assertIn("id=\"toggle-result-panel\"", html)
        self.assertIn("<div id=\"python-panel\" class=\"result-section\">", html)
        self.assertNotIn("<details", html)
        self.assertNotIn("<summary>Generated Python</summary>", html)
        self.assertIn("Generated Python", html)
        self.assertIn("save-graph", html)
        self.assertIn("id=\"status-message\"", html)
        self.assertIn("graph-canvas", html)
        self.assertIn("data-canvas-space", html)
        self.assertIn("edge-layer", html)
        self.assertIn("<marker", html)
        self.assertNotIn("property-editor", html)
        self.assertIn("ChatInputNode", js)
        self.assertIn("ChatOutputNode", js)
        self.assertIn("PromptBuilderNode", js)
        self.assertIn("prompt_builder", js)
        self.assertIn("system_prompt", js)
        self.assertIn("user_prompt", js)
        self.assertIn("tools_json", js)
        self.assertIn("context_json", js)
        self.assertIn("node.type === \"prompt_builder\"", js)
        self.assertIn("generatePython", js)
        self.assertIn("edges", js)
        self.assertIn("GraphExecutor", js)
        self.assertIn("graph.connect(", js)
        self.assertIn("Graph()", js)
        self.assertIn("pointerdown", js)
        self.assertIn("connectionDrag", js)
        self.assertIn("startConnectionDrag", js)
        self.assertIn("moveConnectionDrag", js)
        self.assertIn("finishConnectionDrag", js)
        self.assertIn("preview-connection", js)
        self.assertIn("data-compatible", js)
        self.assertNotIn("handlePortClick", js)
        self.assertIn("viewportState", js)
        self.assertIn("applyViewportTransform", js)
        self.assertIn("wheel", js)
        self.assertIn("startCanvasPan", js)
        self.assertIn("data-port", js)
        self.assertIn("marker-end", js)
        self.assertIn("apiUrl(\"/api/graph\")", js)
        self.assertIn("apiUrl(\"/api/nodes\")", js)
        self.assertIn("loadNodeCatalog", js)
        self.assertIn("nodeSearchEl", js)
        self.assertIn("filterNodeCatalog", js)
        self.assertIn("node-group", js)
        self.assertIn("categoryForNode", js)
        self.assertIn("node-search", js)
        self.assertIn("renderCode()", js)
        self.assertIn("updateProperty", js)
        self.assertIn("resultRailCollapsed", js)
        self.assertIn("toggleResultPanel", js)
        self.assertIn("renderPlannerLayout", js)
        self.assertIn("result-collapsed", js)
        self.assertIn("result-rail collapsed", js)
        self.assertIn("Could not load node catalog", js)
        self.assertIn("let nodeCatalog = []", js)
        self.assertNotIn("const nodeCatalog = [", js)
        self.assertIn("setStatus(", js)
        self.assertIn("Could not reach FlainBot server", js)
        self.assertIn("127.0.0.1:8765", js)
        self.assertIn("ProviderCallNode", js)
        self.assertIn("provider_call", js)
        self.assertIn("provider_id", js)
        self.assertIn("providers", js)
        self.assertIn("apiUrl(\"/api/providers\")", js)
        self.assertIn("loadProviders", js)
        self.assertIn("saveProviders", js)
        self.assertIn("renderProviders", js)
        self.assertIn("renderProviderSelect", js)
        self.assertIn("node.type === \"provider_call\"", js)
        self.assertIn("const form = event.currentTarget", js)
        self.assertIn("form.reset()", js)
        self.assertNotIn("event.currentTarget.reset()", js)
        self.assertNotIn("node.type === \"openai\" || node.type === \"anthropic\"", js)
        self.assertIn("<form class=\"node-properties\"", js)
        self.assertIn("node-properties", js)
        self.assertIn("autocomplete=\"off\"", js)
        self.assertIn("event.preventDefault()", js)

    def test_chat_view_is_in_single_index_shell(self):
        html = (ROOT / "frontend" / "index.html").read_text(encoding="utf-8")
        js = (ROOT / "frontend" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "frontend" / "styles.css").read_text(encoding="utf-8")

        self.assertIn("FlainBot Chat", html)
        self.assertIn("data-view=\"chat\"", html)
        self.assertIn("id=\"chat-form\"", html)
        self.assertIn("id=\"messages\"", html)
        self.assertNotIn("chat.css", html)
        self.assertNotIn("chat.js", html)
        self.assertIn("setActiveView", js)
        self.assertIn("hashchange", js)
        self.assertIn("apiUrl(\"/api/chat\")", js)
        self.assertIn("127.0.0.1:8765", js)
        self.assertIn(".chat-shell", css)
        self.assertIn("html,\nbody", css)
        self.assertIn("overflow: hidden", css)
        self.assertIn("height: 100vh", css)
        self.assertIn("main {\n  min-height: 0;\n  overflow: hidden;", css)
        self.assertIn("grid-template-rows: auto minmax(0, 1fr)", css)
        self.assertIn("overflow-y: auto", css)
        self.assertIn(".planner-workbench.result-collapsed", css)
        self.assertIn(".result-rail.collapsed .result-toggle", css)
        self.assertIn("height: 100%", css)
        self.assertIn("writing-mode: vertical-rl", css)
        self.assertNotIn(".result-toggle-hint", css)
        self.assertNotIn(".result-section > summary", css)
        self.assertIn("height: 100%", css)

    def test_standalone_chat_assets_were_removed(self):
        self.assertFalse((ROOT / "frontend" / "chat.html").exists())
        self.assertFalse((ROOT / "frontend" / "chat.js").exists())
        self.assertFalse((ROOT / "frontend" / "chat.css").exists())


if __name__ == "__main__":
    unittest.main()
